cache:
  directories:
    - front/node_modules
    - back/vendor

matrix:
  include:
    - language: node_js
      node_js: 10
      before_install:
        - cd front/
      install: 
        - npm install
      script:
        - npm test
        - npm run build