language: bash

sudo: required

env:
  global:
    - NGINX_PORT=3000
    - SERVER_NAME=php-docker.local
    - PHP_ADDRESS=php
    - TIMEZONE='Europe/Paris'
    - DOCKER_USER=travis
    - DOCKER_USER_ID=2000
    - DB_USER=ensiie
    - DB_PASSWORD=ensiie
    - DB_PORT_EXTERNAL=5431
    - DB_HOST=postgres
    - SECRET=secret123

addons:
  ssh_known_hosts: 51.38.237.240

before_install:
  - eval "$(ssh-agent -s)"
  - make start

install:
  - make composer.install
  - make npm.install

script:
  - make phpunit.run
  - make npmunit.run

after_success:
  - make npm.build

before_deploy:
  - make composer.install.prod
  - openssl aes-256-cbc -K $encrypted_d7678493f959_key -iv $encrypted_d7678493f959_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: feature/set-cicd-for-travis
