sudo: required

language: bash

services:
  - docker

script:
  - docker pull node:alpine
  - docker run -v $PWD/front:/usr/src/app -ti node:alpine sh -c "cd /usr/src/app && npm install"
  - docker run -v $PWD/front:/usr/src/app -ti node:alpine sh -c "cd /usr/src/app && npm test"
  - docker run -v $PWD/front:/usr/src/app -ti node:alpine sh -c "cd /usr/src/app && npm run build"
