version: '3.3'
services:
  nginx:
    build: ./.docker/nginx-php
    restart: "no"
    depends_on:
      - php
    ports :
      - "${NGINX_PORT}:80"
    environment:
      - "SERVER_NAME=${SERVER_NAME}"
      - "PHP_ADDRESS=${PHP_ADDRESS}"
      - "TZ=${TIMEZONE}"
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - "ensiie"

  php:
    build:
      context: ./.docker/php-fpm/
      args:
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_USER_ID: ${DOCKER_USER_ID}
    restart: "no"
    environment:
      TZ: ${TIMEZONE}
      XDEBUG_CONFIG: remote_host=${REMOTE_HOST}
      SSH_AUTH_SOCK: /ssh-agent
      DB_NAME: ${DB_USER}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MAILING_LIST: ${MAILING_LIST}
      SUBJECT_HEADER: ${SUBJECT_HEADER}
      ADRESS: ${ADRESS}
      SMTP_PORT: ${SMTP_PORT}
    volumes:
      - .:/var/www/html
      - $SSH_AUTH_SOCK:/ssh-agent
    working_dir: /var/www/html
    user: "${DOCKER_USER}"
    entrypoint:
      - ""
    command:
      - "php-fpm"
    networks:
      - "ensiie"

  postgres:
    build:
      context: ./.docker/postgres
    ports:
      - ${DB_PORT_EXTERNAL}
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - "ensiie"

  #pgadmin:
  # image: dpage/pgadmin4
  #  ports:
  #    - "80:80"
  #  environment:
  #    - "PGADMIN_DEFAULT_EMAIL=josephine.barthel11@gmail.com"
  #    - "PGADMIN_DEFAULT_PASSWORD=ensiie"
  #  networks:
  #    - "ensiie"


  # exim:
  #  image: elsdoerfer/exim-sender
  #  ports:
  #    - "4444:26"
  #  environment:
  #    - "ALLOWED_HOSTS=127.0.0.1"
  #  networks:
  #    - "ensiie"

networks:
    ensiie:
        driver: bridge


















